# Makefile used to compile thehotel management system
#also includes a clean option
all: hotel.o
	@echo '*Compiling Program'
	@gcc -o hotels hotel.o
hotel.o: hotel.c
	 @echo '*Compiling Program'
	 @gcc -c hotel.c
clean:
	 @echo '*cleaning object and executable files
	 rm -f *.o hotels